### PR TITLE
Add setting for always reverting to online

### PR DESCRIPTION
**Pull request by bobbyl140**
Implemented feature as described in #6.

### CODE REVIEW

**Comment by RoguedBear** [comment]
I tried your changes and they look good to me! I also appreciate you following the same variable naming style.

However would it be possible for you to add your changes to `src/AutoIdleOnAFK/config.json` and `src/AutoIdleOnAFK/index.js` instead, since the file under `release/` is generated from the code in `src/`

Also thank you for taking time out to contribute to the plugin

**Comment by bobbyl140** [comment]
I updated both those files. Is there some way I should undo the changes to the file in the `release/` folder? Also, I was unsure how you would want the changelog to look, so I left that as it was. If you would like me to simply replace everything with a description of the new feature, I can do so.

**Comment by RoguedBear** [comment]
I'll undo those changes in `release/` from my side. You can leave the changelog too since I'll be bundling your changes and a patch for #8 in one update.

I'll also do some refactoring on your branch before merging if you dont mind me doing that.

again, thank you for your time putting these changes together

**Comment by RoguedBear** [comment]
also, in the changelog should I address you by your github username or some other username (like discord one maybe)?

**Comment by bobbyl140** [comment]
Thank you very much! Glad to contribute. Shall I close this pr, or wait till the update is released?

**Comment by bobbyl140** [comment]
> also, in the changelog should I address you by your github username or some other username (like discord one maybe)?

Just GitHub is great, thanks.

**Comment by RoguedBear** [comment]
> Thank you very much! Glad to contribute. Shall I close this pr, or wait till the update is released?

when i would merge this PR, it would close itself. so now you just have to wait till the update is released which i'll be done doing in a few hours

**Comment by bobbyl140** [comment]
Alright. Thank you again!

**Comment by RoguedBear** [comment]
congratulations on your first PR!

**Pull request merged**
